<?xml version="1.0"?>
<robot name="differential_robot"
  xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.31"/>
  <xacro:property name="base_length" value="0.42"/>
  <xacro:property name="base_height" value="0.18"/>

  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_ygap" value="0.025"/>
  <xacro:property name="wheel_zoff" value="0.05"/>
  <xacro:property name="wheel_xoff" value="0.12"/>

  <!-- Cosmetic properties -->
  <xacro:property name="cabin_length" value="0.30"/>
  <xacro:property name="cabin_width" value="0.25"/>
  <xacro:property name="cabin_height" value="0.15"/>
  <xacro:property name="bumper_length" value="0.05"/>
  <xacro:property name="bumper_width" value="0.35"/>
  <xacro:property name="bumper_height" value="0.10"/>
  <xacro:property name="light_radius" value="0.02"/>
  <xacro:property name="light_xoff_front" value="0.19"/>
  <xacro:property name="light_xoff_rear" value="-0.19"/>
  <xacro:property name="light_yoff" value="0.12"/>
  <xacro:property name="light_zoff" value="0.05"/>

  <!-- Define some commonly used inertial properties -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- Materials for cosmetics -->
  <material name="Blue">
    <color rgba="0 0 1 1"/>
  </material>
  <material name="Yellow">
    <color rgba="1 1 0 1"/>
  </material>
  <material name="Red">
    <color rgba="1 0 0 1"/>
  </material>
  <material name="Gray">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>

  <!-- Robot Base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect * wheel_xoff} ${y_reflect * (base_width/2 + wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="drivewhl_rl" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_rr" x_reflect="-1" y_reflect="-1" />
  <xacro:wheel prefix="drivewhl_fl" x_reflect="1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_fr" x_reflect="1" y_reflect="-1" />

  <!-- Cosmetic Elements -->

  <!-- Cabin -->
  <link name="cabin_link">
    <visual>
      <geometry>
        <box size="${cabin_length} ${cabin_width} ${cabin_height}"/>
      </geometry>
      <material name="Blue"/>
    </visual>
    <xacro:box_inertia m="0.1" w="${cabin_width}" d="${cabin_length}" h="${cabin_height}"/>
  </link>

  <joint name="cabin_joint" type="fixed">
    <parent link="base_link"/>
    <child link="cabin_link"/>
    <origin xyz="0 0 ${base_height/2 + cabin_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Front Bumper -->
  <link name="front_bumper_link">
    <visual>
      <geometry>
        <box size="${bumper_length} ${bumper_width} ${bumper_height}"/>
      </geometry>
      <material name="Gray"/>
    </visual>
    <xacro:box_inertia m="0.1" w="${bumper_width}" d="${bumper_length}" h="${bumper_height}"/>
  </link>

  <joint name="front_bumper_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_bumper_link"/>
    <origin xyz="${base_length/2 + bumper_length/2} 0 ${bumper_height/2 - base_height/2 + wheel_zoff}" rpy="0 0 0"/>
  </joint>

  <!-- Rear Bumper -->
  <link name="rear_bumper_link">
    <visual>
      <geometry>
        <box size="${bumper_length} ${bumper_width} ${bumper_height}"/>
      </geometry>
      <material name="Gray"/>
    </visual>
    <xacro:box_inertia m="0.1" w="${bumper_width}" d="${bumper_length}" h="${bumper_height}"/>
  </link>

  <joint name="rear_bumper_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_bumper_link"/>
    <origin xyz="${-base_length/2 - bumper_length/2} 0 ${bumper_height/2 - base_height/2 + wheel_zoff}" rpy="0 0 0"/>
  </joint>

  <!-- Lights Macro -->
  <xacro:macro name="light" params="prefix x y z color">
    <link name="${prefix}_link">
      <visual>
        <geometry>
          <sphere radius="${light_radius}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
      <xacro:sphere_inertia m="0.01" r="${light_radius}"/>
    </link>

    <joint name="${prefix}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <xacro:light prefix="headlight_left" x="${light_xoff_front}" y="${light_yoff}" z="${light_zoff}" color="Yellow" />
  <xacro:light prefix="headlight_right" x="${light_xoff_front}" y="${-light_yoff}" z="${light_zoff}" color="Yellow" />
  <xacro:light prefix="taillight_left" x="${light_xoff_rear}" y="${light_yoff}" z="${light_zoff}" color="Red" />
  <xacro:light prefix="taillight_right" x="${light_xoff_rear}" y="${-light_yoff}" z="${light_zoff}" color="Red" />

  <!-- Gazebo Differential Drive Plugin -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">

      <!-- Joint names (multiple for skid-steer) -->
      <left_joint>drivewhl_rl_joint</left_joint>
      <left_joint>drivewhl_fl_joint</left_joint>
      <right_joint>drivewhl_rr_joint</right_joint>
      <right_joint>drivewhl_fr_joint</right_joint>

      <!-- Robot geometry -->
      <wheel_separation>${base_width + 2*wheel_ygap}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <!-- Publication parameters -->
      <odom_publish_frequency>30</odom_publish_frequency>
      <topic>cmd_vel</topic>
    </plugin>

    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">

      <topic>joint_states</topic>

      <!-- Publish states for all wheels -->
      <joint_name>drivewhl_rl_joint</joint_name>
      <joint_name>drivewhl_rr_joint</joint_name>
      <joint_name>drivewhl_fl_joint</joint_name>
      <joint_name>drivewhl_fr_joint</joint_name>
    </plugin>
  </gazebo>

  <!-- Wheel friction settings (reduced mu2 for skid-turning) -->
  <gazebo reference="drivewhl_rl_link">
    <mu1>1.0</mu1>
    <mu2>0.5</mu2>
  </gazebo>
  
  <gazebo reference="drivewhl_rr_link">
    <mu1>1.0</mu1>
    <mu2>0.5</mu2>
  </gazebo>

  <gazebo reference="drivewhl_fl_link">
    <mu1>0.01</mu1>
    <mu2>0.01</mu2>
  </gazebo>
  
  <gazebo reference="drivewhl_fr_link">
    <mu1>0.01</mu1>
    <mu2>0.01</mu2>
  </gazebo>

</robot>